var hierarchy =
[
    [ "Hash::_ht", "struct_hash_1_1__ht.html", null ],
    [ "MemPage::_OvflCell", "struct_mem_page_1_1___ovfl_cell.html", null ],
    [ "ACommad", "class_a_commad.html", null ],
    [ "ACommand", "class_a_command.html", [
      [ "ComentCommand", "class_coment_command.html", [
        [ "CommandCreateComent", "class_command_create_coment.html", null ],
        [ "CommandDeleteComent", "class_command_delete_coment.html", null ],
        [ "CommandFindComent", "class_command_find_coment.html", null ],
        [ "CommandFindPostComents", "class_command_find_post_coments.html", null ],
        [ "CommandUpdateComent", "class_command_update_coment.html", null ]
      ] ],
      [ "PostCommand", "class_post_command.html", [
        [ "CommandCreatePost", "class_command_create_post.html", null ],
        [ "CommandDeletePost", "class_command_delete_post.html", null ],
        [ "CommandFindAllPost", "class_command_find_all_post.html", null ],
        [ "CommandFindPost", "class_command_find_post.html", null ],
        [ "CommandFindUserPost", "class_command_find_user_post.html", null ],
        [ "CommandUpdatePost", "class_command_update_post.html", null ]
      ] ],
      [ "UserCommand", "class_user_command.html", [
        [ "CommandCreateUser", "class_command_create_user.html", null ],
        [ "CommandDeleteUser", "class_command_delete_user.html", null ],
        [ "CommandFindUser", "class_command_find_user.html", null ],
        [ "CommandFindUsers", "class_command_find_users.html", null ],
        [ "CommandUpdateUser", "class_command_update_user.html", null ]
      ] ]
    ] ],
    [ "AggInfo", "struct_agg_info.html", null ],
    [ "AggInfo::AggInfo_col", "struct_agg_info_1_1_agg_info__col.html", null ],
    [ "AggInfo::AggInfo_func", "struct_agg_info_1_1_agg_info__func.html", null ],
    [ "analysisInfo", "structanalysis_info.html", null ],
    [ "AttachKey", "struct_attach_key.html", null ],
    [ "AuthContext", "struct_auth_context.html", null ],
    [ "AutoincInfo", "struct_autoinc_info.html", null ],
    [ "VdbeFunc::AuxData", "struct_vdbe_func_1_1_aux_data.html", null ],
    [ "BasicType", "class_basic_type.html", [
      [ "ComentText", "class_coment_text.html", null ],
      [ "Date", "class_date.html", null ],
      [ "Evaluation", "class_evaluation.html", null ],
      [ "Identify", "class_identify.html", null ],
      [ "Password", "class_password.html", null ],
      [ "PostText", "class_post_text.html", null ],
      [ "UserName", "class_user_name.html", null ]
    ] ],
    [ "Bitvec", "struct_bitvec.html", null ],
    [ "BtCursor", "struct_bt_cursor.html", null ],
    [ "BtLock", "struct_bt_lock.html", null ],
    [ "Btree", "struct_btree.html", null ],
    [ "BtreeMutexArray", "struct_btree_mutex_array.html", null ],
    [ "BtShared", "struct_bt_shared.html", null ],
    [ "Builder", "class_builder.html", null ],
    [ "BusyHandler", "struct_busy_handler.html", null ],
    [ "CellInfo", "struct_cell_info.html", null ],
    [ "CollSeq", "struct_coll_seq.html", null ],
    [ "Column", "struct_column.html", null ],
    [ "Coment", "class_coment.html", null ],
    [ "ComentProtocol", "class_coment_protocol.html", [
      [ "LNComent", "class_l_n_coment.html", null ]
    ] ],
    [ "compareInfo", "structcompare_info.html", null ],
    [ "CountCtx", "struct_count_ctx.html", null ],
    [ "DateTime", "struct_date_time.html", null ],
    [ "Db", "struct_db.html", null ],
    [ "DbFixer", "struct_db_fixer.html", null ],
    [ "et_info", "structet__info.html", null ],
    [ "Expr", "struct_expr.html", null ],
    [ "ExprList", "struct_expr_list.html", null ],
    [ "ExprList::ExprList_item", "struct_expr_list_1_1_expr_list__item.html", null ],
    [ "ExprSpan", "struct_expr_span.html", null ],
    [ "FileChunk", "struct_file_chunk.html", null ],
    [ "FilePoint", "struct_file_point.html", null ],
    [ "FKey", "struct_f_key.html", null ],
    [ "FuncDef", "struct_func_def.html", null ],
    [ "FuncDefHash", "struct_func_def_hash.html", null ],
    [ "FuncDestructor", "struct_func_destructor.html", null ],
    [ "Hash", "struct_hash.html", null ],
    [ "HashElem", "struct_hash_elem.html", null ],
    [ "IdList", "struct_id_list.html", null ],
    [ "IdList::IdList_item", "struct_id_list_1_1_id_list__item.html", null ],
    [ "Incrblob", "struct_incrblob.html", null ],
    [ "Index", "struct_index.html", null ],
    [ "IndexSample", "struct_index_sample.html", null ],
    [ "InitData", "struct_init_data.html", null ],
    [ "InitialIUControler", "class_initial_i_u_controler.html", null ],
    [ "IntegrityCk", "struct_integrity_ck.html", null ],
    [ "IUComentProtocol", "class_i_u_coment_protocol.html", [
      [ "ComentControler", "class_coment_controler.html", null ]
    ] ],
    [ "IUPostProtocol", "class_i_u_post_protocol.html", [
      [ "PostControler", "class_post_controler.html", null ]
    ] ],
    [ "IUUserProtocol", "class_i_u_user_protocol.html", [
      [ "UserControler", "class_user_controler.html", null ]
    ] ],
    [ "KeyInfo", "struct_key_info.html", null ],
    [ "LikeOp", "struct_like_op.html", null ],
    [ "LimitVal", "struct_limit_val.html", null ],
    [ "LogicError", "class_logic_error.html", null ],
    [ "Lookaside", "struct_lookaside.html", null ],
    [ "LookasideSlot", "struct_lookaside_slot.html", null ],
    [ "Mem", "struct_mem.html", null ],
    [ "MemJournal", "struct_mem_journal.html", null ],
    [ "MemPage", "struct_mem_page.html", null ],
    [ "Module", "struct_module.html", null ],
    [ "NameContext", "struct_name_context.html", null ],
    [ "Pager", "struct_pager.html", null ],
    [ "PagerSavepoint", "struct_pager_savepoint.html", null ],
    [ "Parse", "struct_parse.html", null ],
    [ "PCache", "struct_p_cache.html", null ],
    [ "PCache1", "struct_p_cache1.html", null ],
    [ "PercistenceError", "class_percistence_error.html", null ],
    [ "PercistenceProtocol", "class_percistence_protocol.html", [
      [ "PersistenceControler", "class_persistence_controler.html", null ]
    ] ],
    [ "PersistenceProtocol", "class_persistence_protocol.html", null ],
    [ "PgFreeslot", "struct_pg_freeslot.html", null ],
    [ "PgHdr", "struct_pg_hdr.html", null ],
    [ "PgHdr1", "struct_pg_hdr1.html", null ],
    [ "Post", "class_post.html", null ],
    [ "PostProtocol", "class_post_protocol.html", [
      [ "LNPost", "class_l_n_post.html", null ]
    ] ],
    [ "RowSet", "struct_row_set.html", null ],
    [ "RowSetChunk", "struct_row_set_chunk.html", null ],
    [ "RowSetEntry", "struct_row_set_entry.html", null ],
    [ "Savepoint", "struct_savepoint.html", null ],
    [ "Schema", "struct_schema.html", null ],
    [ "FKey::sColMap", "struct_f_key_1_1s_col_map.html", null ],
    [ "ScratchFreeslot", "struct_scratch_freeslot.html", null ],
    [ "Select", "struct_select.html", null ],
    [ "SelectDest", "struct_select_dest.html", null ],
    [ "Set", "struct_set.html", null ],
    [ "sqlite3", "structsqlite3.html", null ],
    [ "sqlite3_api_routines", "structsqlite3__api__routines.html", null ],
    [ "sqlite3_backup", "structsqlite3__backup.html", null ],
    [ "sqlite3_context", "structsqlite3__context.html", null ],
    [ "sqlite3_file", "structsqlite3__file.html", null ],
    [ "sqlite3_index_info::sqlite3_index_constraint", "structsqlite3__index__info_1_1sqlite3__index__constraint.html", null ],
    [ "sqlite3_index_info::sqlite3_index_constraint_usage", "structsqlite3__index__info_1_1sqlite3__index__constraint__usage.html", null ],
    [ "sqlite3_index_info", "structsqlite3__index__info.html", null ],
    [ "sqlite3_index_info::sqlite3_index_orderby", "structsqlite3__index__info_1_1sqlite3__index__orderby.html", null ],
    [ "sqlite3_io_methods", "structsqlite3__io__methods.html", null ],
    [ "sqlite3_mem_methods", "structsqlite3__mem__methods.html", null ],
    [ "sqlite3_module", "structsqlite3__module.html", null ],
    [ "sqlite3_mutex", "structsqlite3__mutex.html", null ],
    [ "sqlite3_mutex_methods", "structsqlite3__mutex__methods.html", null ],
    [ "sqlite3_pcache_methods", "structsqlite3__pcache__methods.html", null ],
    [ "sqlite3_rtree_geometry", "structsqlite3__rtree__geometry.html", null ],
    [ "sqlite3_vfs", "structsqlite3__vfs.html", null ],
    [ "sqlite3_vtab", "structsqlite3__vtab.html", null ],
    [ "sqlite3_vtab_cursor", "structsqlite3__vtab__cursor.html", null ],
    [ "Sqlite3Config", "struct_sqlite3_config.html", null ],
    [ "sqlite3::sqlite3InitInfo", "structsqlite3_1_1sqlite3_init_info.html", null ],
    [ "SrcList", "struct_src_list.html", null ],
    [ "SrcList::SrcList_item", "struct_src_list_1_1_src_list__item.html", null ],
    [ "StarTesteTipos", "class_star_teste_tipos.html", null ],
    [ "StrAccum", "struct_str_accum.html", null ],
    [ "SubProgram", "struct_sub_program.html", null ],
    [ "SumCtx", "struct_sum_ctx.html", null ],
    [ "Table", "struct_table.html", null ],
    [ "TableLock", "struct_table_lock.html", null ],
    [ "TabResult", "struct_tab_result.html", null ],
    [ "TesteBasico", "class_teste_basico.html", [
      [ "TesteTBComentText", "class_teste_t_b_coment_text.html", null ],
      [ "TesteTBDate", "class_teste_t_b_date.html", null ],
      [ "TesteTBEvaluation", "class_teste_t_b_evaluation.html", null ],
      [ "TesteTBIdentify", "class_teste_t_b_identify.html", null ],
      [ "TesteTBPassword", "class_teste_t_b_password.html", null ],
      [ "TesteTBPostText", "class_teste_t_b_post_text.html", null ],
      [ "TesteTBUserName", "class_teste_t_b_user_name.html", null ]
    ] ],
    [ "Token", "struct_token.html", null ],
    [ "TrigEvent", "struct_trig_event.html", null ],
    [ "Trigger", "struct_trigger.html", null ],
    [ "TriggerPrg", "struct_trigger_prg.html", null ],
    [ "TriggerStep", "struct_trigger_step.html", null ],
    [ "unixFile", "structunix_file.html", null ],
    [ "unixFileId", "structunix_file_id.html", null ],
    [ "unixInodeInfo", "structunix_inode_info.html", null ],
    [ "unixShm", "structunix_shm.html", null ],
    [ "unixShmNode", "structunix_shm_node.html", null ],
    [ "UnixUnusedFd", "struct_unix_unused_fd.html", null ],
    [ "UnpackedRecord", "struct_unpacked_record.html", null ],
    [ "User", "class_user.html", null ],
    [ "UserProtocol", "class_user_protocol.html", [
      [ "LNUser", "class_l_n_user.html", null ]
    ] ],
    [ "Vdbe", "struct_vdbe.html", null ],
    [ "VdbeCursor", "struct_vdbe_cursor.html", null ],
    [ "VdbeFrame", "struct_vdbe_frame.html", null ],
    [ "VdbeFunc", "struct_vdbe_func.html", null ],
    [ "VdbeOp", "struct_vdbe_op.html", null ],
    [ "VdbeOpList", "struct_vdbe_op_list.html", null ],
    [ "VTable", "struct_v_table.html", null ],
    [ "vxworksFileId", "structvxworks_file_id.html", null ],
    [ "Wal", "struct_wal.html", null ],
    [ "WalCkptInfo", "struct_wal_ckpt_info.html", null ],
    [ "WalIndexHdr", "struct_wal_index_hdr.html", null ],
    [ "WalIterator", "struct_wal_iterator.html", null ],
    [ "Walker", "struct_walker.html", null ],
    [ "WalIterator::WalSegment", "struct_wal_iterator_1_1_wal_segment.html", null ],
    [ "WhereAndInfo", "struct_where_and_info.html", null ],
    [ "WhereClause", "struct_where_clause.html", null ],
    [ "WhereCost", "struct_where_cost.html", null ],
    [ "WhereInfo", "struct_where_info.html", null ],
    [ "WhereLevel", "struct_where_level.html", null ],
    [ "WhereMaskSet", "struct_where_mask_set.html", null ],
    [ "WhereOrInfo", "struct_where_or_info.html", null ],
    [ "WherePlan", "struct_where_plan.html", null ],
    [ "WhereTerm", "struct_where_term.html", null ],
    [ "Parse::yColCache", "struct_parse_1_1y_col_cache.html", null ],
    [ "YYMINORTYPE", "union_y_y_m_i_n_o_r_t_y_p_e.html", null ],
    [ "yyParser", "structyy_parser.html", null ],
    [ "yyStackEntry", "structyy_stack_entry.html", null ]
];